export const ADD_PROJECT = 'ADD_PROJECT';
export const REMOVE_PROJECT = 'REMOVE_PROJECT';
export const ADD_TASK_TO_PROJECT = 'ADD_TASK_TO_PROJECT';
export const REMOVE_TASK_FROM_PROJECT = 'REMOVE_TASK_FROM_PROJECT';

export const ADD_TASK = 'ADD_TASK';
export const TOGGLE_TASK = 'TOGGLE_TASK';
export const REMOVE_TASK = 'REMOVE_TASK';
